[package]
name = "rust-calendar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
chrono = "0.4.19"
num-traits = "0.2.14"
